services:
  - type: web
    name: issatkass-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin@cluster0.mongodb.net/university-portal?retryWrites=true&w=majority # Replace with your MongoDB Connection String
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://frontend-peach-mu-14.vercel.app
